#!/usr/bin/env ruby

require "bundler/setup"
require "csv_auditor"

options = {}

option_parser = OptionParser.new do |opts|
  opts.banner = "Usage: audit [options]"

  opts.on "-c", "--config .csv_auditor.csv", "Configuration file path"
end

option_parser.parse!(into: options)

if options[:config].nil?
  puts option_parser.help
  exit 1
end

CsvAuditor.configure do |config|
  config.config_file_path = options[:config]
end

CsvAuditor.run
